### ISSUE TITLE
Render phaser in HTML5 frame on localhost:3000.

### ISSUE THREAD

**Issue by mattattaq** [aallbrig/carpe-noctem#9]
Render a phaser environment for the game to render in.

**Comment by mattattaq** [comment]
Completed by @aallbrig 
![screen shot 2017-08-12 at 1 08 40 pm](https://user-images.githubusercontent.com/13422887/29242824-d07c0e12-7f61-11e7-883d-923bec4e9fd9.png)

**Comment by aallbrig** [comment]
Closing as this as been completed.
